<?php
/**
 * class-affiliates-attributes-wordpress.php
 *
 * Copyright 2011 "kento" Karim Rahimpur - www.itthinx.com
 *
 * This code is provided subject to the license granted.
 * Unauthorized use and distribution is prohibited.
 * See COPYRIGHT.txt and LICENSE.txt
 *
 * This code is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This header and all notices must be kept intact.
 *
 * @author Karim Rahimpur
 * @package affiliates-pro
 * @since affiliates-pro 1.0.0
 */

if ( !defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * System-specific attributes implementation.
 */
class Affiliates_Attributes_WordPress extends Affiliates_Attributes {

	/**
	 * View
	 *
	 * @param int $affiliate_id
	 */
	function view( $affiliate_id ) { global $wpdb, $affiliates_options, $affiliates_db; $IX57260 = ''; $IX37709 = new Affiliates_Affiliate_WordPress(); $IX89456 = $IX37709->get_affiliate( $affiliate_id ); if ( $IX89456 ) { $IX35648 = ( is_ssl() ? 'https://' : 'http://' ) . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']; $IX35648 = remove_query_arg( 'action', $IX35648 ); $IX35648 = remove_query_arg( 'affiliate_id', $IX35648 ); $IX55454 = isset( $_POST['row_count'] ) ? intval( $_POST['row_count'] ) : 0; if ($IX55454 <= 0) { $IX55454 = $affiliates_options->get_option( 'affiliates_attributes_per_page', AFFILIATES_HITS_PER_PAGE ); } else { $affiliates_options->update_option('affiliates_attributes_per_page', $IX55454 ); } $IX17325 = isset( $_GET['offset'] ) ? intval( $_GET['offset'] ) : 0; if ( $IX17325 < 0 ) { $IX17325 = 0; } $IX98096 = isset( $_REQUEST['paged'] ) ? intval( $_REQUEST['paged'] ) : 0; if ( $IX98096 < 0 ) { $IX98096 = 0; } $IX57260 .= '<div class="manage-affiliates">' . '<div>' . '<h2>' . __('附屬屬性', 'affiliates' ) . '</h2>' . '</div>'; $IX57260 .= '<div class="manage">' . "<a title='" . __( 'Click to add a new attribute', 'affiliates' ) . "' class='add' href='" . esc_url( $IX35648 ) . "&action=add-attribute&affiliate_id=" . urlencode( $affiliate_id ) . "'><img class='icon' alt='" . __('添加', 'affiliates') . "' src='". AFFILIATES_PRO_PLUGIN_URL ."images/add.png'/><span class='label'>" . __( 'New Attribute', 'affiliates') . "</span></a>" . '</div>'; $IX57260 .= '<div class="affiliates-attributes-overview">'; $IX18427 = array( 'attr_key' => __( 'Id', 'affiliates' ), 'attr_value' => __('價值', 'affiliates' ), 'edit' => __('編輯', 'affiliates' ), 'remove' => __('消除', 'affiliates' ) ); $IX57260 .= '
				<table id="" class="wp-list-table widefat fixed" cellspacing="0">
				<thead>
					<tr>
					'; foreach ( $IX18427 as $IX24518 => $IX24637 ) { $IX57260 .= "<th scope='col' class='$IX24518'>$IX24637</th>"; } $IX57260 .= '</tr>
				</thead>
				<tbody>
				'; $IX59693 = $affiliates_db->get_tablename( "affiliates_attributes" ); $IX72592 = $affiliates_db->get_objects("SELECT * FROM $IX59693 WHERE affiliate_id = %d", $affiliate_id ); if ( !empty( $IX72592 ) ) { $IX95699 = Affiliates_Attributes::get_keys(); $IX54620 = 0; foreach ( $IX72592 as $IX51396 ) { $IX27823 = ''; $IX16590 = ''; $IX57260 .= '<tr class="' . $IX27823 . $IX16590 . ( $IX54620 % 2 == 0 ? 'even' : 'odd' ) . '">'; $IX57260 .= '<td>' . wp_filter_kses( $IX95699[$IX51396->attr_key] ) . '</td>'; $IX67538 = @unserialize( $IX51396->attr_value ); if ( $IX67538 !== false ) { $IX79760 = $IX67538; } else { $IX79760 = $IX51396->attr_value; } if ( is_array( $IX79760 ) ) { $IX79760 = implode( "::", $IX79760 ); } $IX57260 .= '<td>' . wp_filter_kses( $IX79760 ) . '</td>'; $IX57260 .= "<td class='edit'><a href='" . esc_url( $IX35648 ) . "&action=edit-attribute&affiliate_id=" . urlencode( $affiliate_id ) . "&attr_key=" . urlencode( $IX51396->attr_key ) . "' alt='" . __('編輯', 'affiliates') . "'><img src='". AFFILIATES_PRO_PLUGIN_URL ."images/edit.png'/></a></td>"; $IX57260 .= "<td class='remove'><a href='" . esc_url( $IX35648 ) . "&action=remove-attribute&affiliate_id=" . urlencode( $affiliate_id ) . "&attr_key=" . urlencode( $IX51396->attr_key ) . "' alt='" . __('消除', 'affiliates') . "'><img src='". AFFILIATES_PRO_PLUGIN_URL ."images/remove.png'/></a></td>"; $IX57260 .= '</tr>'; $IX54620++; } $IX57260 .= '</table>'; $IX57260 .= '</td>'; $IX57260 .= '</tr>'; } else { $IX57260 .= '<tr><td colspan="' . count( $IX18427 ) . '">' . __('沒有結果。', 'affiliates' ) . '</td></tr>'; } $IX57260 .= '</tbody>'; $IX57260 .= '</table>'; $IX57260 .= '</div>'; $IX57260 .= '</div>'; } echo $IX57260; }

	/**
	 * Show add attribute form.
	 */
	function add( $affiliate_id ) { global $affiliates_db; if ( !current_user_can( AFFILIATES_ADMINISTER_AFFILIATES ) ) { wp_die( __( '拒絕訪問。', 'affiliates' ) ); } affiliates_pro_admin_notices(); $IX59637 = ( is_ssl() ? 'https://' : 'http://' ) . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']; $IX59637 = remove_query_arg( 'action', $IX59637 ); $IX59637 = remove_query_arg( 'affiliate_id', $IX59637 ); $IX90448 = esc_url( $IX59637 ) . "&action=edit&affiliate_id=" . urlencode( $affiliate_id ); $IX59637 = remove_query_arg( 'paged', $IX59637 ); $affiliate_id = isset( $_POST['affiliate_id'] ) ? $_POST['affiliate_id'] : $affiliate_id; $IX58037 = isset( $_POST['attr-key-field'] ) ? $_POST['attr-key-field'] : ''; $IX84993 = isset( $_POST['attr-value-field'] ) ? $_POST['attr-value-field'] : ''; $IX27030 = array(); $IX46302 = $affiliates_db->get_tablename( 'affiliates_attributes' ); $IX93615 = $affiliates_db->get_objects( "SELECT * FROM $IX46302 WHERE affiliate_id = %d", $affiliate_id ); foreach( $IX93615 as $IX17374 ) { $IX27030[] = $IX17374->attr_key; } $IX97277 = '<select id="attr-key-field" name="attr-key-field" class="attr-key-field">'; $IX40514 = Affiliates_Attributes::get_keys(); if ( !get_option( Affiliates_Referral::DEFAULT_REFERRAL_CALCULATION_KEY, null ) ) { unset( $IX40514[Affiliates_Attributes::REFERRAL_AMOUNT] ); unset( $IX40514[Affiliates_Attributes::REFERRAL_AMOUNT_METHOD] ); unset( $IX40514[Affiliates_Attributes::REFERRAL_RATE] ); } foreach( $IX40514 as $IX89082 => $IX63949 ) { if ( !in_array( $IX89082, $IX27030 ) ) { $IX66956 = $IX58037 == $IX89082 ? ' selected="selected" ' : ''; $IX97277 .= '<option value="' . esc_attr( $IX89082 ) . '" ' . $IX66956 . '>' . wp_filter_kses( $IX63949 ) . '</option>'; } } $IX97277 .= '</select>'; $IX38227 = '<div class="manage-affiliates">' . '<div>' . '<h1>' . __('添加新屬性', 'affiliates' ) . '</h1>' . '</div>' . '<form id="add-attribute" action="' . esc_url( $IX59637 ) . '" method="post">' . '<div class="affiliate new">' . '<div class="field">' . '<label for="attr-key-field" class="field-label first required">' .__('鑰匙', 'affiliates' ) . '</label>' . $IX97277 . '</div>' . '<div class="field">' . '<label for="attr-value-field" class="field-label first required">' .__('價值', 'affiliates' ) . '</label>' . '<input id="attr-value-field" name="attr-value-field" class="attr-value-field" type="text" value="' . esc_attr( $IX84993 ) . '"/>' . '</div>' . '<div class="field">' . wp_nonce_field( plugin_basename( __FILE__ ), AFFILIATES_ADMIN_AFFILIATES_NONCE, true, false ) . '<input class="button button-primary" type="submit" value="' . __('添加', 'affiliates' ) . '"/>' . '<input type="hidden" value="' . esc_attr( $affiliate_id ) . '" name="affiliate_id"/>' . '<input type="hidden" value="add-attribute" name="action"/>' . ' ' . '<a class="cancel button" href="' . $IX90448 . '">' . __('取消', 'affiliates' ) . '</a>' . '</div>' . '</div>' . '</form>' . '</div>'; echo $IX38227; }

	/**
	 * Handle add affiliate form submission.
	 */
	function add_submit() { global $wpdb, $affiliates_db, $affiliates_pro_admin_messages; $IX54863 = true; if ( !current_user_can( AFFILIATES_ADMINISTER_AFFILIATES ) ) { wp_die( __( '拒絕訪問。', 'affiliates' ) ); } if ( !isset( $_POST[AFFILIATES_ADMIN_AFFILIATES_NONCE] ) || !wp_verify_nonce( $_POST[AFFILIATES_ADMIN_AFFILIATES_NONCE], plugin_basename( __FILE__ ) ) ) { wp_die( __( '拒絕訪問。', 'affiliates' ) ); } $IX77468 = $affiliates_db->get_tablename( 'affiliates_attributes' ); $IX43179 = isset( $_POST['affiliate_id'] ) ? $_POST['affiliate_id'] : null; $IX98714 = isset( $_POST['attr-key-field'] ) ? $_POST['attr-key-field'] : null; $IX80343 = isset( $_POST['attr-value-field'] ) ? $_POST['attr-value-field'] : null; if ( $IX80343 !== null ) { $IX80343 = Affiliates_Attributes::validate_value( $IX98714, $IX80343 ); if ( $IX80343 !== false ) { if ( is_array( $IX80343 ) || is_object( $IX80343 ) ) { $IX80343 = serialize( $IX80343 ); } } else { $IX80343 = null; } } $IX70670 = false; if ( ( $IX98714 == Affiliates_Attributes::COUPONS ) && !empty( $IX80343 ) ) { $IX94306 = explode( ",", $IX80343 ); foreach( $IX94306 as $IX76158 ) { $IX76158 = trim( $IX76158 ); $IX91297 = self::get_affiliate_for_coupon( $IX76158 ); if ( ( $IX91297 !== null ) && ( $IX91297 != $IX43179 ) ) { $affiliates_pro_admin_messages[] = '<div class="error">' . sprintf( __('優惠券不得分配給多個聯營公司。優惠券代碼 <strong>%s</strong> 已分配給 ID 為 %d 的聯營公司。', 'affiliates'), $IX76158, $IX91297 ) . '</div>'; $IX70670 = true; } } } if ( $IX70670 ) { return false; } if ( !empty( $IX43179 ) && Affiliates_Attributes::validate_key( $IX98714 ) && ( $IX80343 !== null ) ) { if ( !$affiliates_db->get_value( "SELECT * FROM $IX77468 WHERE affiliate_id = %d AND attr_key = %s", $IX43179, $IX98714 ) ) { if ( $affiliates_db->query( "INSERT INTO $IX77468 SET affiliate_id=%d, attr_key=%s, attr_value=%s", $IX43179, $IX98714, $IX80343 ) ) { do_action( 'affiliates_added_attribute', $IX43179, $IX98714, $IX80343 ); } } else { $affiliates_pro_admin_messages[] = '<div class="error">' . __('重複鍵', 'affiliates' ) . '</div>'; $IX54863 = false; } } else { $affiliates_pro_admin_messages[] = '<div class="error">' . __('無效數據', 'affiliates' ) . '</div>'; $IX54863 = false; } return $IX54863; }

	/**
	 * Show edit attribute form.
	 */
	function edit( $affiliate_id, $attr_key ) { global $affiliates_db; if ( !current_user_can( AFFILIATES_ADMINISTER_AFFILIATES ) ) { wp_die( __( '拒絕訪問。', 'affiliates' ) ); } affiliates_pro_admin_notices(); $IX79805 = ( is_ssl() ? 'https://' : 'http://' ) . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']; $IX79805 = remove_query_arg( 'action', $IX79805 ); $IX79805 = remove_query_arg( 'affiliate_id', $IX79805 ); $IX22593 = esc_url( $IX79805 ) . "&action=edit&affiliate_id=" . urlencode( $affiliate_id ); $IX79805 = remove_query_arg( 'paged', $IX79805 ); $IX34022 = $affiliates_db->get_tablename( 'affiliates_attributes' ); $IX43474 = $affiliates_db->get_value( "SELECT attr_value FROM $IX34022 WHERE affiliate_id = %d AND attr_key = %s", $affiliate_id, $attr_key ); $affiliate_id = isset( $_POST['affiliate_id'] ) ? $_POST['affiliate_id'] : $affiliate_id; $attr_key = isset( $_POST['attr-key-field'] ) ? $_POST['attr-key-field'] : $attr_key; $IX43474 = isset( $_POST['attr-value-field'] ) ? $_POST['attr-value-field'] : $IX43474; $IX29723 = @unserialize( $IX43474 ); if ( $IX29723 === false ) { $IX29723 = $IX43474; } if ( is_array( $IX29723 ) ) { $IX29723 = implode( "::", $IX29723 ); } $IX96835 = Affiliates_Attributes::get_keys(); $IX28058 = '<div class="manage-affiliates">' . '<div>' . '<h1>' . __('編輯屬性', 'affiliates' ) . '</h1>' . '</div>' . '<form id="edit-attribute" action="' . esc_url( $IX79805 ) . '" method="post">' . '<div class="affiliate-attribute edit">' . '<div class="field">' . '<label for="attr-key-field" class="field-label first required">' .__('鑰匙', 'affiliates' ) . '</label>' . '<input readonly="readonly" id="attr-name-field" name="attr-name-field" class="attr-name-field" type="text" value="' . esc_attr( $IX96835[$attr_key] ) . '"/>' . '<input type="hidden" name="attr-key-field" value="' . esc_attr( $attr_key ) . '"/>' . '</div>' . '<div class="field">' . '<label for="attr-value-field" class="field-label first required">' .__('價值', 'affiliates' ) . '</label>' . '<input id="attr-value-field" name="attr-value-field" class="attr-value-field" type="text" value="' . esc_attr( $IX29723 ) . '"/>' . '</div>' . '<div class="field">' . wp_nonce_field( plugin_basename( __FILE__ ), AFFILIATES_ADMIN_AFFILIATES_NONCE, true, false ) . '<input class="button button-primary" type="submit" value="' . __('節省', 'affiliates' ) . '"/>' . '<input type="hidden" value="' . esc_attr( $affiliate_id ) . '" name="affiliate_id"/>' . '<input type="hidden" value="edit-attribute" name="action"/>' . ' ' . '<a class="cancel button" href="' . $IX22593 . '">' . __('取消', 'affiliates' ) . '</a>' . '</div>' . '</div>' . '</form>' . '</div>'; echo $IX28058; }

	/**
	 * Handle edit attribute form submission.
	 */
	function edit_submit() { global $wpdb, $affiliates_db, $affiliates_pro_admin_messages; $IX33854 = true; if ( !current_user_can( AFFILIATES_ADMINISTER_AFFILIATES ) ) { wp_die( __( '拒絕訪問。', 'affiliates' ) ); } if ( !isset( $_POST[AFFILIATES_ADMIN_AFFILIATES_NONCE] ) || !wp_verify_nonce( $_POST[AFFILIATES_ADMIN_AFFILIATES_NONCE], plugin_basename( __FILE__ ) ) ) { wp_die( __( '拒絕訪問。', 'affiliates' ) ); } $IX17497 = $affiliates_db->get_tablename( 'affiliates_attributes' ); $IX56961 = isset( $_POST['affiliate_id'] ) ? $_POST['affiliate_id'] : null; $IX54591 = isset( $_POST['attr-key-field'] ) ? $_POST['attr-key-field'] : null; $IX91422 = isset( $_POST['attr-value-field'] ) ? $_POST['attr-value-field'] : null; if ( $IX91422 !== null ) { $IX91422 = Affiliates_Attributes::validate_value( $IX54591, $IX91422 ); if ( $IX91422 !== false ) { if ( is_array( $IX91422 ) || is_object( $IX91422 ) ) { $IX91422 = serialize( $IX91422 ); } } else { $IX91422 = null; } } $IX78264 = false; if ( ( $IX54591 == Affiliates_Attributes::COUPONS ) && !empty( $IX91422 ) ) { $IX19415 = explode( ",", $IX91422 ); foreach( $IX19415 as $IX13799 ) { $IX13799 = trim( $IX13799 ); $IX70552 = self::get_affiliate_for_coupon( $IX13799 ); if ( ( $IX70552 !== null ) && ( $IX70552 != $IX56961 ) ) { $affiliates_pro_admin_messages[] = '<div class="error">' . sprintf( __('優惠券不得分配給多個聯營公司。優惠券代碼 <strong>%s</strong> 已分配給 ID 為 %d 的聯營公司。', 'affiliates'), $IX13799, $IX70552 ) . '</div>'; $IX78264 = true; } } } if ( $IX78264 ) { return false; } if ( !empty( $IX56961 ) && Affiliates_Attributes::validate_key( $IX54591 ) && ( $IX91422 !== null ) ) { if ( $IX49602 = $affiliates_db->get_value( "SELECT attr_value FROM $IX17497 WHERE affiliate_id = %d AND attr_key = %s", $IX56961, $IX54591 ) ) { if ( $affiliates_db->query( "UPDATE $IX17497 SET attr_value=%s WHERE affiliate_id=%d AND attr_key=%s", $IX91422 , $IX56961, $IX54591 ) ) { do_action( 'affiliates_updated_attribute', $IX56961, $IX54591, $IX49602, $IX91422 ); } } else { $affiliates_pro_admin_messages[] = '<div class="error">' . __( 'Invalid key', 'affiliates' ) . '</div>'; $IX33854 = false; } } else { $affiliates_pro_admin_messages[] = '<div class="error">' . __('無效數據', 'affiliates' ) . '</div>'; $IX33854 = false; } return $IX33854; }

	/**
	 * Show remove attribute form.
	 */
	function remove( $affiliate_id, $attr_key ) { global $affiliates_db; if ( !current_user_can( AFFILIATES_ADMINISTER_AFFILIATES ) ) { wp_die( __( '拒絕訪問。', 'affiliates' ) ); } affiliates_pro_admin_notices(); $IX66253 = ( is_ssl() ? 'https://' : 'http://' ) . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']; $IX66253 = remove_query_arg( 'action', $IX66253 ); $IX66253 = remove_query_arg( 'affiliate_id', $IX66253 ); $IX15728 = esc_url( $IX66253 ) . "&action=edit&affiliate_id=" . urlencode( $affiliate_id ); $IX66253 = remove_query_arg( 'paged', $IX66253 ); $IX62096 = $affiliates_db->get_tablename( 'affiliates_attributes' ); $IX66551 = $affiliates_db->get_value( "SELECT attr_value FROM $IX62096 WHERE affiliate_id = %d AND attr_key = %s", $affiliate_id, $attr_key ); $affiliate_id = isset( $_POST['affiliate_id'] ) ? $_POST['affiliate_id'] : $affiliate_id; $attr_key = isset( $_POST['attr-key-field'] ) ? $_POST['attr-key-field'] : $attr_key; $IX66551 = isset( $_POST['attr-value-field'] ) ? $_POST['attr-value-field'] : $IX66551; $IX93273 = @unserialize( $IX66551 ); if ( $IX93273 === false ) { $IX93273 = $IX66551; } if ( is_array( $IX93273 ) ) { $IX93273 = implode( "::", $IX93273 ); } $IX34168 = Affiliates_Attributes::get_keys(); $IX73180 = '<div class="manage-affiliates">' . '<div>' . '<h1>' . __('刪除屬性', 'affiliates' ) . '</h1>' . '</div>' . '<form id="remove-attribute" action="' . esc_url( $IX66253 ) . '" method="post">' . '<div class="affiliate-attribute remove">' . '<div class="field">' . '<label for="attr-key-field" class="field-label first required">' .__('鑰匙', 'affiliates' ) . '</label>' . '<input readonly="readonly" id="attr-name-field" name="attr-name-field" class="attr-name-field" type="text" value="' . esc_attr( $IX34168[$attr_key] ) . '"/>' . '<input type="hidden" name="attr-key-field" value="' . esc_attr( $attr_key ) . '"/>' . '</div>' . '<div class="field">' . '<label for="attr-value-field" class="field-label first required">' .__('價值', 'affiliates' ) . '</label>' . '<input readonly="readonly" id="attr-value-field" name="attr-value-field" class="attr-value-field" type="text" value="' . esc_attr( $IX93273 ) . '"/>' . '</div>' . '<div class="field">' . wp_nonce_field( plugin_basename( __FILE__ ), AFFILIATES_ADMIN_AFFILIATES_NONCE, true, false ) . '<input class="button button-primary" type="submit" value="' . __('消除', 'affiliates' ) . '"/>' . '<input type="hidden" value="' . esc_attr( $affiliate_id ) . '" name="affiliate_id"/>' . '<input type="hidden" value="remove-attribute" name="action"/>' . ' ' . '<a class="cancel button" href="' . $IX15728 . '">' . __('取消', 'affiliates' ) . '</a>' . '</div>' . '</div>' . '</form>' . '</div>'; echo $IX73180; }

	/**
	 * Handle remove attribute form submission.
	 */
	function remove_submit() { global $wpdb, $affiliates_db, $affiliates_pro_admin_messages; $IX50855 = true; if ( !current_user_can( AFFILIATES_ADMINISTER_AFFILIATES ) ) { wp_die( __( '拒絕訪問。', 'affiliates' ) ); } if ( !isset( $_POST[AFFILIATES_ADMIN_AFFILIATES_NONCE] ) || !wp_verify_nonce( $_POST[AFFILIATES_ADMIN_AFFILIATES_NONCE], plugin_basename( __FILE__ ) ) ) { wp_die( __( '拒絕訪問。', 'affiliates' ) ); } $IX92179 = $affiliates_db->get_tablename( 'affiliates_attributes' ); $IX82973 = isset( $_POST['affiliate_id'] ) ? $_POST['affiliate_id'] : null; $IX16163 = isset( $_POST['attr-key-field'] ) ? $_POST['attr-key-field'] : null; if ( !( empty( $IX82973 ) || empty( $IX16163 ) ) ) { $IX53000 = $affiliates_db->get_value( "SELECT attr_value FROM $IX92179 WHERE affiliate_id = %d AND attr_key = %s", $IX82973, $IX16163 ); if ( $affiliates_db->query( "DELETE FROM $IX92179 WHERE affiliate_id=%d AND attr_key=%s", $IX82973, $IX16163 ) ) { do_action( 'affiliates_removed_attribute', $IX82973, $IX16163, $IX53000 ); } } else { $IX50855 = false; } return $IX50855; }

	/**
	 * Returns the affiliate id that the given $coupon code is assigned to
	 * or null if the code is not yet assigned to an affiliate.
	 *
	 * @param string $coupon coupon code
	 * @return int affiliate id of the affiliate assigned, null otherwise
	 */
	public static function get_affiliate_for_coupon( $coupon ) { global $affiliates_db; $IX65077 = $affiliates_db->get_tablename( "affiliates_attributes" ); $IX64274 = $affiliates_db->get_objects( "SELECT * FROM $IX65077 WHERE attr_key = %s AND attr_value LIKE %s", Affiliates_Attributes::COUPONS, '%' . $affiliates_db->esc_like( $coupon ) . '%' ); $IX21851 = null; foreach( $IX64274 as $IX42847 ) { $IX91702 = explode( ",", $IX42847->attr_value ); foreach( $IX91702 as $IX83693 ) { $IX83693 = trim( $IX83693 ); if ( apply_filters( 'affiliates_coupons_equality_test', $IX83693 === $coupon, $IX83693, $coupon ) ) { $IX21851 = $IX42847->affiliate_id; break; } } if ( $IX21851 !== null ) { break; } } return apply_filters( 'affiliates_coupon_affiliate_id', $IX21851, $coupon ); }

	/**
	 * Returns the coupons for the affiliate.
	 * @param int $affiliate_id
	 * @return array of string, coupons associated to the affiliate
	 * @since 2.3.2
	 */
	public static function get_coupons_for_affiliate( $affiliate_id ) { global $affiliates_db; $IX78313 = array(); $IX83898 = $affiliates_db->get_tablename( 'affiliates_attributes' ); if ( $IX40007 = $affiliates_db->get_value( "SELECT attr_value FROM $IX83898 WHERE affiliate_id = %d AND attr_key = %s", intval( $affiliate_id ), Affiliates_Attributes::COUPONS ) ) { $IX78313 = explode( ',', $IX40007 ); } return $IX78313; }

	/**
	 * Sets the coupons for the affiliate.
	 * @param int $affiliate_id
	 * @param array $coupons
	 * @since 2.3.2
	 */
	public static function set_coupons_for_affiliate( $affiliate_id, $coupons = array() ) { global $affiliates_db; $affiliate_id = intval( $affiliate_id ); $IX22300 = array(); foreach( $coupons as $IX61741 ) { $IX61741 = trim( $IX61741 ); if ( strlen( $IX61741 ) > 0 ) { $IX39613 = self::get_affiliate_for_coupon( $IX61741 ); if ( ( $IX39613 === null ) || ( $IX39613 == $affiliate_id ) ) { $IX22300[] = $IX61741; } } } $coupons = $IX22300; $IX92085 = self::get_coupons_for_affiliate( $affiliate_id ); if ( $IX92085 != $coupons ) { $IX10766 = $affiliates_db->get_tablename( 'affiliates_attributes' ); if ( count( $coupons ) == 0 ) { if ( $affiliates_db->query( "DELETE FROM $IX10766 WHERE affiliate_id=%d AND attr_key=%s", $affiliate_id, $IX61005 ) ) { do_action( 'affiliates_removed_attribute', $affiliate_id, Affiliates_Attributes::COUPONS, implode( ',', $IX92085 ) ); } } else { if ( $IX61926 = $affiliates_db->get_value( "SELECT attr_value FROM $IX10766 WHERE affiliate_id = %d AND attr_key = %s", $affiliate_id, Affiliates_Attributes::COUPONS ) ) { if ( $affiliates_db->query( "UPDATE $IX10766 SET attr_value=%s WHERE affiliate_id=%d AND attr_key=%s", implode( ',', $coupons ) , $affiliate_id, Affiliates_Attributes::COUPONS ) ) { do_action( 'affiliates_updated_attribute', $affiliate_id, Affiliates_Attributes::COUPONS, $IX61926, implode( ',', $coupons ) ); } } else { if ( $affiliates_db->query( "INSERT INTO $IX10766 SET affiliate_id=%d, attr_key=%s, attr_value=%s", $affiliate_id, Affiliates_Attributes::COUPONS, implode( ',', $coupons ) ) ) { do_action( 'affiliates_added_attribute', $affiliate_id, Affiliates_Attributes::COUPONS, implode( ',', $coupons ) ); } } } } }
}
